### ISSUE TITLE
IPV6

### ISSUE THREAD

**Issue by haroldLuiz** [impalex/knockonports#9] opened 2020-04-27 18:14 UTC
even though knockd doesn't support IPV6, the APP trys to use IPV6 if there is a "AAAA" DNS register.

Would be great if there was a IPV6/IPV4 switch on the knock app entry

**Comment by impalex** [comment] 2020-04-27 21:31
Can't confirm it yet, but I'll investigate this issue.

**Comment by impalex** [comment] 2020-04-27 21:36
What kind of packets (UDP/TCP/ICMP) are you using in your sequence?

**Comment by haroldLuiz** [comment] 2020-04-27 21:53
I "randomly" alternate between tcp and udp.

**Comment by impalex** [comment] 2020-04-28 01:17
Okay, I found the cause of this bug. I'll fix this issue.
Please use the IP address instead of the host name as a workaround until the next version.

**Comment by impalex** [comment] 2020-04-30 16:03
Fixed in 1.1.5, update is live.
Thanks.

**Closed as completed by impalex** 2020-04-30 16:03 UTC
Labels: bug
